epochs: 200
output_dir: output_dir

model:
  name: MoCo
  backbone:
    name: ResNet
    depth: 50
  neck:
    name: NonLinearNeckV1
    in_channels: 2048
    hid_channels: 2048
    out_channels: 128
    with_avg_pool: True
  head:
    name: ContrastiveHead
    temperature: 0.2

dataloader:
  train:
    num_workers: 4
    sampler:
      batch_size: 32
      shuffle: true
      drop_last: true
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: False
      return_two_sample: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          scale: [0.2, 1.]
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
          p: 0.5
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]

lr_scheduler:
  name: CosineAnnealingDecay
  learning_rate: 0.015
  T_max: 200


optimizer:
  name: Momentum
  weight_decay: 0.0001

log_config:
    name: LogHook
    interval: 50
