epochs: 100
output_dir: output_dir

model:
  name: Classification
  backbone:
    name: ResNet
    depth: 50
    frozen_stages: 4
    # freeze_bn: True
  head:
    name: ClasHead
    with_avg_pool: true
    in_channels: 2048
    num_classes: 1000

dataloader:
  train:
    num_workers: 4
    sampler:
      batch_size: 64
      shuffle: true
      drop_last: False
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
  val:
    num_workers: 4
    sampler:
      batch_size: 64
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]

lr_scheduler:
  name: MultiStepDecay
  learning_rate: 30.0
  milestones: [60, 80]


optimizer:
  name: Momentum
  weight_decay: 0.0

log_config:
    name: LogHook
    interval: 50

custom_config:
  - name: EvaluateHook
