epochs: 100
use_simclr_iters: True
global_batch_size: 4096
output_dir: output_dir

model:
  name: SimCLR
  backbone:
    name: ResNet
    depth: 50
    frozen_stages: 4
  neck:
    name: NonLinearNeckfc3
    in_channels: 2048
    hid_channels: 2048
    out_channels: 128
    with_avg_pool: False
  head:
    name: SimCLRContrastiveHead
    temperature: 0.1

dataloader:
  train:
    num_workers: 6
    sampler:
      batch_size: 128
      
      shuffle: true
      drop_last: true
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      mode: 'train'
      return_label: False
      return_two_sample: True
      transforms:
        - name: RandomResizedCrop
          size: 32
          scale: [0.1, 1.]
          interpolation: bicubic
      view_trans1:
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: Normalize
      view_trans2:
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: Normalize
  val:
    num_workers: 4
    sampler:
      batch_size: 512
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012
      return_label: True
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]





lr_scheduler:
  name: simclrCosineWarmup
  learning_rate_scaling: sqrt
  total_images: 1281167
  warmup_epochs: 10
  start_lr: 0
  end_lr: 1.0
  T_max: 200


optimizer:
  name: LarsMomentumOptimizer
  momentum: 0.9
  lars_weight_decay: 0.0001
  exclude_from_weight_decay: ['scale', 'offset', 'b_0']
  
log_config:
    name: LogHook
    interval: 30


